### PR TITLE
"Tutorial0-helloworld"

### PR DESCRIPTION
**Pull request by aditipate**
Hi Rashed! Here's Tutorial0, please accept this pull request, thanks.

### CODE REVIEW

**Comment by RashedRifat** [comment]
Hey, just a quick thing, if you could rename the file to your name (like RashedRifat), that would be great! It's just easier for us to format and keep track of these things

**Comment by aditipate** [comment]
Yes I can do that!
________________________________

**Comment by aditipate** [comment]
renamed file, hopefully it works

**Comment by RashedRifat** [comment]
Yup, I can see the changes! Great to have you on board and welcome to the Insights Team!

**Pull request merged**
